spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/angular
    username: root
    password: 1234
  kafka:
    bootstrap-servers: localhost:9092
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
app:
  topic:
    foo: foo.t
logging:
  level:
    root: WARN
    org.springframework.web: INFO
    com.memorynotfound: DEBUG